# Site settings
title: adriandiaz.ca
email: web.art@adriandiaz.ca
description: "The home of Adrian Diaz's artist portfolio."
baseurl: "http://www.adriandiaz.ca"
url: "http://www.adriandiaz.ca"
twitter_username: adgr72
github_username:  adriandgr

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty


collections:
  contributors:
    output: true
    permalink: /contributors/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Site owner
owner:
  name: Adrian Diaz
  display_name: Adrian
  web: http://www.adriandiaz.ca
  email: web.art@adriandiaz.ca
  twitter: adgr72
  github: adriandgr
  gravatar: 1092e44f33d0454dfb580e19f3687ce8
  bio: "A Vancouver-based artist"
  avatar: bio/shifting.jpg # 160x160 px image for author byline
  google:
    plus: +AdrianDiazArt
    ad-client: ca-pub-(+16digit)
    ad-slot: (10digitNumber)
  disqus-shortname: adriandiaz
